"""
KANG BANG - shared Blender authoring library.

Everything in assets/ is generated by these scripts: there are no downloaded or
third-party meshes anywhere in the project. Running `npm run assets` reproduces
the entire art set from source.

Design rules encoded here:
  * Low poly by construction. Shapes are built from vertex lists, not from
    primitives that are then decimated, so triangle counts are exact and
    predictable.
  * Y up, -Z forward, metres. Matches the engine and glTF's convention after
    the exporter's +Y-up conversion.
  * One material per visual role (body / trim / energy / glass). Fewer materials
    means fewer draw calls once the client merges them.
  * Every object gets a deliberate name; the client looks up sockets like
    `SOCKET_muzzle` by name rather than by index.

Usage from a generator script:

    import lib_kang as N
    N.reset_scene()
    body = N.box("body", (0, 0, 0), (0.08, 0.09, 0.5), N.MAT_BODY)
    N.export_glb("wpn_example")
"""

from __future__ import annotations

import math
import os
import sys

import bpy
import mathutils

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR = os.path.dirname(SCRIPT_DIR)
REPO_ROOT = os.path.dirname(ASSETS_DIR)
SOURCE_DIR = os.path.join(ASSETS_DIR, "source")
EXPORT_DIR = os.path.join(REPO_ROOT, "packages", "client", "public", "assets", "models")

os.makedirs(SOURCE_DIR, exist_ok=True)
os.makedirs(EXPORT_DIR, exist_ok=True)


def log(message: str) -> None:
    print(f"[kang] {message}", flush=True)


# ---------------------------------------------------------------------------
# Material identities
# ---------------------------------------------------------------------------

# (name, base_color, metallic, roughness, emission_color, emission_strength)
#
# Grounded materials: real firearms and kit, not energy weapons. Three things
# changed together here, and each one was causing a visible problem.
#
#   Emission strengths were 5-7 on the `energy` materials. The client dropped its
#   filmic tone curve when the palette went grounded, so anything over 1.0 clips
#   flat to pure white - every weapon and character wore white slabs where its
#   trim should be. Nothing here emits above 0.8 now, and almost nothing emits at
#   all, because a rifle does not glow.
#
#   Metallic was 0.72-0.90 on the body and trim. A metallic surface with no
#   environment map to reflect renders black, and the client no longer ships one
#   (it was 12 MB). Real gun finishes are coated, phosphated or polymer, so low
#   metallic is both cheaper and more accurate.
#
#   The `energy_*` names are kept as aliases so no generator has to change, but
#   they are now paint and marking colours. What was a glowing cyan strip is a
#   painted blue panel.
MATERIAL_LIBRARY = {
    # Weapon and armour bodies: phosphate grey, polymer black, worn aluminium.
    "ns_body": ((0.29, 0.31, 0.33, 1.0), 0.25, 0.52, None, 0.0),
    "ns_body_dark": ((0.13, 0.14, 0.15, 1.0), 0.18, 0.62, None, 0.0),
    "ns_body_light": ((0.60, 0.62, 0.64, 1.0), 0.22, 0.48, None, 0.0),
    "ns_trim": ((0.09, 0.09, 0.10, 1.0), 0.30, 0.44, None, 0.0),
    "ns_grip": ((0.10, 0.10, 0.11, 1.0), 0.02, 0.86, None, 0.0),

    # Marking and accent colours. Painted, not lit.
    "ns_energy_cyan": ((0.16, 0.38, 0.55, 1.0), 0.05, 0.60, None, 0.0),
    "ns_energy_lime": ((0.24, 0.45, 0.24, 1.0), 0.05, 0.62, None, 0.0),
    "ns_energy_amber": ((0.68, 0.45, 0.14, 1.0), 0.05, 0.58, None, 0.0),
    "ns_energy_violet": ((0.42, 0.34, 0.46, 1.0), 0.05, 0.62, None, 0.0),
    # Off-white plastic and painted steel, e.g. sights and stencils.
    "ns_energy_white": ((0.84, 0.85, 0.84, 1.0), 0.05, 0.52, None, 0.0),

    "ns_glass": ((0.62, 0.70, 0.74, 0.30), 0.0, 0.10, None, 0.0),
    "ns_skin": ((0.76, 0.58, 0.45, 1.0), 0.0, 0.64, None, 0.0),

    # Team identification: a painted armband and a helmet patch. Faint emission
    # only, so it stays readable across a room without glowing.
    "ns_team": ((0.20, 0.42, 0.66, 1.0), 0.05, 0.58, (0.20, 0.42, 0.66), 0.25),
    # Tinted eye protection. Dark and slightly glossy, no glow.
    "ns_visor": ((0.09, 0.11, 0.13, 1.0), 0.20, 0.18, None, 0.0),

    "ns_rubber": ((0.08, 0.08, 0.09, 1.0), 0.02, 0.90, None, 0.0),
    # Brass cases, the one genuinely metallic thing left, and small enough that
    # having nothing to reflect does not read as a fault.
    "ns_brass": ((0.68, 0.54, 0.26, 1.0), 0.55, 0.36, None, 0.0),
    "ns_crate": ((0.52, 0.38, 0.20, 1.0), 0.06, 0.74, None, 0.0),
    # Safety yellow. Real hazard markings are retroreflective, so a hint of
    # emission is defensible and keeps them legible in shadow.
    "ns_hazard": ((0.84, 0.70, 0.18, 1.0), 0.05, 0.58, (0.84, 0.70, 0.18), 0.18),
}

MAT_BODY = "ns_body"
MAT_BODY_DARK = "ns_body_dark"
MAT_BODY_LIGHT = "ns_body_light"
MAT_TRIM = "ns_trim"
MAT_GRIP = "ns_grip"
MAT_CYAN = "ns_energy_cyan"
MAT_LIME = "ns_energy_lime"
MAT_AMBER = "ns_energy_amber"
MAT_VIOLET = "ns_energy_violet"
MAT_WHITE = "ns_energy_white"
MAT_GLASS = "ns_glass"
MAT_SKIN = "ns_skin"
MAT_TEAM = "ns_team"
MAT_VISOR = "ns_visor"
MAT_RUBBER = "ns_rubber"
MAT_BRASS = "ns_brass"
MAT_CRATE = "ns_crate"
MAT_HAZARD = "ns_hazard"


def get_material(name: str) -> bpy.types.Material:
    """Fetch or create one of the library materials."""
    existing = bpy.data.materials.get(name)
    if existing is not None:
        return existing

    spec = MATERIAL_LIBRARY.get(name)
    if spec is None:
        spec = MATERIAL_LIBRARY[MAT_BODY]
    base_color, metallic, roughness, emission, emission_strength = spec

    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    bsdf = nodes.get("Principled BSDF")
    if bsdf is None:
        bsdf = nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.inputs["Base Color"].default_value = base_color
    bsdf.inputs["Metallic"].default_value = metallic
    bsdf.inputs["Roughness"].default_value = roughness
    if "Emission Color" in bsdf.inputs and emission is not None:
        bsdf.inputs["Emission Color"].default_value = (*emission, 1.0)
        bsdf.inputs["Emission Strength"].default_value = emission_strength
    elif "Emission" in bsdf.inputs and emission is not None:
        bsdf.inputs["Emission"].default_value = (*emission, 1.0)
        if "Emission Strength" in bsdf.inputs:
            bsdf.inputs["Emission Strength"].default_value = emission_strength
    if base_color[3] < 1.0:
        mat.blend_method = "BLEND"
        if "Alpha" in bsdf.inputs:
            bsdf.inputs["Alpha"].default_value = base_color[3]
    return mat


# ---------------------------------------------------------------------------
# Scene setup
# ---------------------------------------------------------------------------


def reset_scene() -> None:
    """Empty the file completely so a generator always starts clean."""
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.length_unit = "METERS"
    # A single sun so the .blend is viewable when opened by a human.
    sun_data = bpy.data.lights.new("NeonSun", type="SUN")
    sun_data.energy = 3.0
    sun = bpy.data.objects.new("NeonSun", sun_data)
    sun.rotation_euler = (math.radians(55), 0.0, math.radians(35))
    scene.collection.objects.link(sun)


def _link(obj: bpy.types.Object) -> None:
    bpy.context.scene.collection.objects.link(obj)


def mesh_from_data(
    name: str,
    verts: list[tuple[float, float, float]],
    faces: list[tuple[int, ...]],
    material: str,
    smooth: bool = False,
) -> bpy.types.Object:
    """Create an object from explicit vertex/face data."""
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(verts, [], faces)
    mesh.validate(verbose=False)
    mesh.update()
    if smooth:
        for poly in mesh.polygons:
            poly.use_smooth = True
    mesh.materials.append(get_material(material))
    obj = bpy.data.objects.new(name, mesh)
    _link(obj)
    return obj


# ---------------------------------------------------------------------------
# Primitives - all built from explicit data for exact triangle counts
# ---------------------------------------------------------------------------

_BOX_FACES = [
    (0, 1, 2, 3),  # -Z
    (4, 7, 6, 5),  # +Z
    (0, 4, 5, 1),  # -Y
    (2, 6, 7, 3),  # +Y
    (0, 3, 7, 4),  # -X
    (1, 5, 6, 2),  # +X
]


def box(
    name: str,
    center: tuple[float, float, float],
    size: tuple[float, float, float],
    material: str = MAT_BODY,
    rotation: tuple[float, float, float] = (0.0, 0.0, 0.0),
    taper: tuple[float, float] = (1.0, 1.0),
) -> bpy.types.Object:
    """
    Axis-aligned box (before `rotation`, in degrees).

    `taper` scales the +Z face in X and Y, which turns a box into a truncated
    wedge - the single most useful shape for low-poly weapon bodies.
    """
    hx, hy, hz = size[0] / 2.0, size[1] / 2.0, size[2] / 2.0
    tx, ty = taper
    verts = [
        (-hx, -hy, -hz),
        (hx, -hy, -hz),
        (hx, hy, -hz),
        (-hx, hy, -hz),
        (-hx * tx, -hy * ty, hz),
        (hx * tx, -hy * ty, hz),
        (hx * tx, hy * ty, hz),
        (-hx * tx, hy * ty, hz),
    ]
    obj = mesh_from_data(name, verts, list(_BOX_FACES), material)
    obj.location = center
    obj.rotation_euler = tuple(math.radians(a) for a in rotation)
    return obj


def cylinder(
    name: str,
    center: tuple[float, float, float],
    radius: float,
    length: float,
    segments: int = 8,
    material: str = MAT_BODY,
    axis: str = "Z",
    radius_top: float | None = None,
    rotation: tuple[float, float, float] = (0.0, 0.0, 0.0),
    smooth: bool = True,
) -> bpy.types.Object:
    """N-gon prism/cone along `axis`. 8 segments reads as round at game scale."""
    if radius_top is None:
        radius_top = radius
    half = length / 2.0
    verts: list[tuple[float, float, float]] = []
    for i in range(segments):
        a = (i / segments) * math.tau
        verts.append((math.cos(a) * radius, math.sin(a) * radius, -half))
    for i in range(segments):
        a = (i / segments) * math.tau
        verts.append((math.cos(a) * radius_top, math.sin(a) * radius_top, half))

    faces: list[tuple[int, ...]] = []
    for i in range(segments):
        j = (i + 1) % segments
        faces.append((i, j, segments + j, segments + i))
    faces.append(tuple(reversed(range(segments))))
    faces.append(tuple(range(segments, segments * 2)))

    obj = mesh_from_data(name, verts, faces, material, smooth=smooth)
    rot = list(rotation)
    if axis.upper() == "X":
        rot[1] += 90.0
    elif axis.upper() == "Y":
        rot[0] += 90.0
    obj.location = center
    obj.rotation_euler = tuple(math.radians(a) for a in rot)
    return obj


def wedge(
    name: str,
    center: tuple[float, float, float],
    size: tuple[float, float, float],
    material: str = MAT_BODY,
    rotation: tuple[float, float, float] = (0.0, 0.0, 0.0),
) -> bpy.types.Object:
    """Triangular prism rising along +Z."""
    hx, hy, hz = size[0] / 2.0, size[1] / 2.0, size[2] / 2.0
    verts = [
        (-hx, -hy, -hz),
        (hx, -hy, -hz),
        (hx, hy, -hz),
        (-hx, hy, -hz),
        (-hx, hy, hz),
        (hx, hy, hz),
    ]
    faces = [
        (0, 1, 2, 3),
        (3, 2, 5, 4),
        (0, 4, 5, 1),
        (0, 3, 4),
        (1, 5, 2),
    ]
    obj = mesh_from_data(name, verts, faces, material)
    obj.location = center
    obj.rotation_euler = tuple(math.radians(a) for a in rotation)
    return obj


def sphere(
    name: str,
    center: tuple[float, float, float],
    radius: float,
    material: str = MAT_BODY,
    rings: int = 6,
    segments: int = 8,
) -> bpy.types.Object:
    """Low-poly UV sphere; used for helmets, pods and energy cores."""
    verts: list[tuple[float, float, float]] = [(0.0, 0.0, radius)]
    for r in range(1, rings):
        phi = math.pi * r / rings
        z = math.cos(phi) * radius
        rr = math.sin(phi) * radius
        for s in range(segments):
            a = (s / segments) * math.tau
            verts.append((math.cos(a) * rr, math.sin(a) * rr, z))
    verts.append((0.0, 0.0, -radius))

    faces: list[tuple[int, ...]] = []
    for s in range(segments):
        faces.append((0, 1 + s, 1 + (s + 1) % segments))
    for r in range(rings - 2):
        base = 1 + r * segments
        nxt = base + segments
        for s in range(segments):
            s2 = (s + 1) % segments
            faces.append((base + s, nxt + s, nxt + s2, base + s2))
    last = 1 + (rings - 2) * segments
    bottom = len(verts) - 1
    for s in range(segments):
        faces.append((bottom, last + (s + 1) % segments, last + s))

    obj = mesh_from_data(name, verts, faces, material, smooth=True)
    obj.location = center
    return obj


def capsule(
    name: str,
    center: tuple[float, float, float],
    radius: float,
    length: float,
    material: str = MAT_BODY,
    axis: str = "Z",
    segments: int = 8,
) -> bpy.types.Object:
    """Rounded limb segment: a prism with domed caps, joined as one mesh."""
    half = max(0.0001, length / 2.0 - radius)
    verts: list[tuple[float, float, float]] = []
    faces: list[tuple[int, ...]] = []

    rings = [
        (-half - radius * 0.86, radius * 0.34),
        (-half - radius * 0.5, radius * 0.72),
        (-half, radius),
        (half, radius),
        (half + radius * 0.5, radius * 0.72),
        (half + radius * 0.86, radius * 0.34),
    ]
    for z, r in rings:
        for s in range(segments):
            a = (s / segments) * math.tau
            verts.append((math.cos(a) * r, math.sin(a) * r, z))
    for ri in range(len(rings) - 1):
        base = ri * segments
        nxt = base + segments
        for s in range(segments):
            s2 = (s + 1) % segments
            faces.append((base + s, nxt + s, nxt + s2, base + s2))
    # Caps.
    verts.append((0.0, 0.0, -half - radius))
    bottom_tip = len(verts) - 1
    for s in range(segments):
        faces.append((bottom_tip, (s + 1) % segments, s))
    verts.append((0.0, 0.0, half + radius))
    top_tip = len(verts) - 1
    top_base = (len(rings) - 1) * segments
    for s in range(segments):
        faces.append((top_tip, top_base + s, top_base + (s + 1) % segments))

    obj = mesh_from_data(name, verts, faces, material, smooth=True)
    rot = [0.0, 0.0, 0.0]
    if axis.upper() == "X":
        rot[1] = 90.0
    elif axis.upper() == "Y":
        rot[0] = 90.0
    obj.location = center
    obj.rotation_euler = tuple(math.radians(a) for a in rot)
    return obj


def socket(name: str, location: tuple[float, float, float]) -> bpy.types.Object:
    """
    Empty marker exported with the GLB.

    The client reads `SOCKET_muzzle`, `SOCKET_eject` and `SOCKET_grip` to attach
    muzzle flashes, shell ejection and the left-hand IK target, so those points
    live in the art rather than being duplicated as magic numbers in code.
    """
    empty = bpy.data.objects.new(f"SOCKET_{name}", None)
    empty.empty_display_type = "PLAIN_AXES"
    empty.empty_display_size = 0.02
    empty.location = location
    _link(empty)
    return empty


# ---------------------------------------------------------------------------
# Composition helpers
# ---------------------------------------------------------------------------


def mirror_x(obj: bpy.types.Object, name: str | None = None) -> bpy.types.Object:
    """Duplicate an object mirrored across X, keeping winding correct."""
    new_mesh = obj.data.copy()
    dup = bpy.data.objects.new(name or f"{obj.name}_mirror", new_mesh)
    dup.location = (-obj.location.x, obj.location.y, obj.location.z)
    dup.rotation_euler = (obj.rotation_euler.x, -obj.rotation_euler.y, -obj.rotation_euler.z)
    dup.scale = (-obj.scale.x, obj.scale.y, obj.scale.z)
    _link(dup)
    return dup


def join(name: str, objects: list[bpy.types.Object]) -> bpy.types.Object:
    """
    Merge objects into one, preserving per-face materials.

    Merging matters: 18 loose objects per weapon would be 18 draw calls, and the
    client cannot batch across separate glTF nodes.
    """
    objects = [o for o in objects if o is not None and o.type == "MESH"]
    if not objects:
        raise ValueError(f"join({name}) received no meshes")
    bpy.ops.object.select_all(action="DESELECT")
    for o in objects:
        o.select_set(True)
    target = objects[0]
    bpy.context.view_layer.objects.active = target
    if len(objects) > 1:
        bpy.ops.object.join()
    target.name = name
    target.data.name = f"{name}_mesh"
    # Bake transforms so the exported mesh needs no node hierarchy.
    bpy.ops.object.select_all(action="DESELECT")
    target.select_set(True)
    bpy.context.view_layer.objects.active = target
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    return target


def shade_flat(obj: bpy.types.Object) -> None:
    for poly in obj.data.polygons:
        poly.use_smooth = False


def add_uvs(obj: bpy.types.Object) -> None:
    """
    Cheap box-projected UVs.

    The client's materials are procedural, so weapons only need UVs to exist and
    be non-degenerate; a smart-project pass per weapon would triple build time
    for no visible gain.
    """
    mesh = obj.data
    if mesh.uv_layers:
        uv = mesh.uv_layers[0]
    else:
        uv = mesh.uv_layers.new(name="UVMap")
    for poly in mesh.polygons:
        n = poly.normal
        ax, ay, az = abs(n.x), abs(n.y), abs(n.z)
        for li in poly.loop_indices:
            vi = mesh.loops[li].vertex_index
            v = mesh.vertices[vi].co
            if ax >= ay and ax >= az:
                u, w = v.y, v.z
            elif ay >= az:
                u, w = v.x, v.z
            else:
                u, w = v.x, v.y
            uv.data[li].uv = (u * 2.0 + 0.5, w * 2.0 + 0.5)


def triangle_count(obj: bpy.types.Object) -> int:
    total = 0
    for poly in obj.data.polygons:
        total += max(0, len(poly.vertices) - 2)
    return total


def decimate_copy(obj: bpy.types.Object, name: str, ratio: float) -> bpy.types.Object:
    """
    Build an LOD by collapsing edges.

    Only used for assets above ~500 triangles; below that the draw call costs
    more than the geometry and an LOD is wasted effort.
    """
    dup = obj.copy()
    dup.data = obj.data.copy()
    dup.name = name
    dup.data.name = f"{name}_mesh"
    _link(dup)
    bpy.ops.object.select_all(action="DESELECT")
    dup.select_set(True)
    bpy.context.view_layer.objects.active = dup
    mod = dup.modifiers.new("LOD", type="DECIMATE")
    mod.decimate_type = "COLLAPSE"
    mod.ratio = ratio
    bpy.ops.object.modifier_apply(modifier=mod.name)
    return dup


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------


def reorient(mode: str) -> None:
    """
    Rotate the whole scene so the exported glTF lands on the engine's axes.

    Blender is Z-up; glTF is Y-up, and the exporter converts with
    (gx, gy, gz) = (bx, bz, -by). That conversion is why authoring convention
    matters, and why this step exists rather than a fudge factor in the client:

      'yup'  - authored with +Y up and -Z forward (weapons, arms, props).
               Rotating +90 degrees about Blender X maps (x, y, z) to (x, -z, y),
               which after the exporter's conversion reproduces the authored
               axes exactly. Without it a rifle exports pointing at the floor.

      'face' - authored Blender-native (Z up) but facing -Y (characters).
               Rotating 180 degrees about Blender Z leaves the model facing -Z
               after export, which is the engine's forward direction.

    Call immediately before export_glb(), after all joins.
    """
    if mode == "yup":
        matrix = mathutils.Euler((math.radians(90), 0.0, 0.0)).to_matrix().to_4x4()
    elif mode == "face":
        matrix = mathutils.Euler((0.0, 0.0, math.radians(180))).to_matrix().to_4x4()
    else:
        return

    transformed_meshes: set[str] = set()
    for obj in list(bpy.data.objects):
        if obj.type == "MESH":
            # join()/transform_apply have already baked object transforms, so
            # transforming the mesh data is enough - and each mesh datablock
            # must only be transformed once even if several objects share it.
            if obj.data.name not in transformed_meshes:
                obj.data.transform(matrix)
                obj.data.update()
                transformed_meshes.add(obj.data.name)
            obj.location = (matrix @ obj.location.to_4d()).to_3d()
        elif obj.type == "EMPTY":
            obj.location = (matrix @ obj.location.to_4d()).to_3d()


def export_glb(name: str, save_blend: bool = True, objects: list[bpy.types.Object] | None = None) -> str:
    """Write <EXPORT_DIR>/<name>.glb and (optionally) the .blend source."""
    for obj in bpy.data.objects:
        if obj.type == "MESH" and not obj.data.uv_layers:
            add_uvs(obj)

    if objects is not None:
        bpy.ops.object.select_all(action="DESELECT")
        for o in objects:
            o.select_set(True)

    if save_blend:
        blend_path = os.path.join(SOURCE_DIR, f"{name}.blend")
        bpy.ops.wm.save_as_mainfile(filepath=blend_path, check_existing=False, copy=True)

    glb_path = os.path.join(EXPORT_DIR, f"{name}.glb")
    kwargs = dict(
        filepath=glb_path,
        export_format="GLB",
        export_apply=True,
        export_yup=True,
        export_cameras=False,
        export_lights=False,
        export_extras=False,
        use_selection=objects is not None,
        export_normals=True,
        export_texcoords=True,
        export_materials="EXPORT",
        export_animations=True,
    )
    # Draco shrinks these meshes by ~60%, but only when Blender was built with
    # the encoder available. Fall back silently rather than failing the build.
    try:
        bpy.ops.export_scene.gltf(**kwargs, export_draco_mesh_compression_enable=True,
                                  export_draco_mesh_compression_level=6)
    except TypeError:
        bpy.ops.export_scene.gltf(**kwargs)
    except RuntimeError:
        bpy.ops.export_scene.gltf(**kwargs)

    size = os.path.getsize(glb_path)
    tris = sum(triangle_count(o) for o in bpy.data.objects if o.type == "MESH")
    log(f"exported {name}.glb  {size / 1024:.1f} KB  {tris} tris")
    return glb_path


def only_arg(flag: str) -> str | None:
    """Read `-- --only=<value>` from the Blender command line."""
    argv = sys.argv
    if "--" not in argv:
        return None
    for token in argv[argv.index("--") + 1 :]:
        if token.startswith(f"--{flag}="):
            return token.split("=", 1)[1]
    return None


def vec(x: float, y: float, z: float) -> mathutils.Vector:
    return mathutils.Vector((x, y, z))
